# Generated by Django 2.0.6 on 2018-07-04 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.BigIntegerField()),
                ('completed_timestamp', models.BigIntegerField(default=-1)),
                ('time_taken', models.IntegerField(default=-1)),
                ('total_bots', models.IntegerField(default=0)),
                ('server_hostname', models.CharField(default='NOT_FOUND_IN_JSON', max_length=30)),
                ('server_container', models.CharField(default='NOT_FOUND_IN_JSON', max_length=30)),
                ('external_ip', models.CharField(default='0.0.0.0', max_length=30)),
                ('status', models.CharField(default='Started', max_length=20)),
                ('synced', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_ads_found', models.IntegerField(default=0)),
                ('video_list_size', models.IntegerField(default=550)),
                ('remarks', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20)),
                ('state_symbol', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Locations'),
        ),
    ]
