# Generated by Django 2.0.6 on 2018-07-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(default='Running', max_length=20),
        ),
        migrations.AlterField(
            model_name='locations',
            name='state_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='locations',
            name='state_symbol',
            field=models.CharField(max_length=100),
        ),
    ]
