# Generated by Django 2.0.6 on 2018-08-15 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_auto_20180710_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_Found_WatchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField(default=0)),
                ('request_timestamp', models.BigIntegerField(default=0)),
                ('ad_source', models.CharField(default='youtube', max_length=50)),
                ('ad_duration', models.IntegerField(default=0)),
                ('ad_skip_duration', models.IntegerField(default=0)),
                ('ad_system', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('keywords', models.TextField(default='')),
                ('watched_as_ad', models.IntegerField(default=0)),
                ('watched_as_video', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Categories')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Channels')),
            ],
        ),
        migrations.AddField(
            model_name='ad_found_watchlog',
            name='ad_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_video', to='processor.Videos'),
        ),
        migrations.AddField(
            model_name='ad_found_watchlog',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Batch'),
        ),
        migrations.AddField(
            model_name='ad_found_watchlog',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Bots'),
        ),
        migrations.AddField(
            model_name='ad_found_watchlog',
            name='video_watched',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watched', to='processor.Videos'),
        ),
    ]
