# Generated by Django 2.2.3 on 2019-07-15 07:49

from django.db import migrations, models
import django.db.models.deletion
import processor.models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_auto_20180815_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdFile',
            fields=[
                ('id', models.AutoField(db_column='adFile_ID', primary_key=True, serialize=False)),
                ('ad_filepath', models.TextField(null=True)),
                ('collection_type', models.CharField(choices=[(processor.models.CollectionType('CyAds'), 'CyAds'), (processor.models.CollectionType('GoogleTReport'), 'GoogleTReport')], max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='videos',
            name='check_status',
            field=models.CharField(choices=[(processor.models.CheckStatus(0), 0), (processor.models.CheckStatus(1), 1), (processor.models.CheckStatus(2), 2), (processor.models.CheckStatus(3), 3)], default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='videos',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videos',
            name='time_checked',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='videos',
            name='AdFile_ID',
            field=models.ForeignKey(db_column='AdFile_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='processor.AdFile'),
        ),
    ]
